### ISSUE TITLE
Support Delta Lake in GCP Big data Ecosystem

### ISSUE THREAD

**Issue by ChethanUK** [GoogleCloudDataproc/bigdata-interop#271]
Is there any plans to integrate **[Delta Lake](https://delta.io/)** in GCP Big Data Ecosystem?

Delta Lake is very famous for **ACID Transactions, Time Travel, Good Metadata, Support Streaming ingest, Audit History**

Requirements for storage system: https://github.com/delta-io/delta#requirements-for-underlying-storage-systems and https://docs.delta.io/latest/delta-storage.html#configuration-for-hdfs

Since Databricks is not on GCP yet and delta developers don't have GCS development experience and they don't know exact semantics that the GCP FileSystem implementation offers, there are no developments in delta's integration with GCP...

**Comment by yhqs540** [comment]
Right now, you can utilize the [GCS connector](https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage) to use Delta Lake on GCS. You just need to point the Delta Lake table location to use gs://.

**Comment by ChethanUK** [comment]
> separate LogStore to implement things like listFrom with GCS native ways

That will be helpful if you have resources do share them...


> Delta Lake table location to use gs://
Yup, `df.write.format("delta").save("gs://[BUCKET-NAME]/tmp/delta-table")` works..
![img](https://i.imgur.com/qYE2QAX.png)

**Comment by medb** [comment]
You can find out how to use Delta Lake with Dataproc in [this blog post](https://cloud.google.com/blog/products/data-analytics/getting-started-with-new-table-formats-on-dataproc).
