### ISSUE TITLE
com.google.cloud.bigdataoss:gcsio:2.0.0 declaring gson as "provided". Is this correct?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudDataproc/bigdata-interop#275]
Question: com.google.cloud.bigdataoss:gcsio:2.0.0 declares com.google.cloud.bigdataoss:gcsio:2.0.0 as provided dependency. Is this declared as intended?

Maven (and Gradle) does not download "provided" dependencies because the build system assumes the JAR file is available at runtime. 

- https://search.maven.org/artifact/com.google.cloud.bigdataoss/gcsio/2.0.0/jar has
  ```xml
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
    </dependency>
  ```
- Its parent (https://search.maven.org/artifact/com.google.cloud.bigdataoss/bigdataoss-parent/2.0.0/pom) has
  ```xml
      <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>${google.gson.version}</version>
        <scope>provided</scope>
      </dependency>
  ```

### Background
Our static analyzer detected the dependency is marked as provided:
https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1185

**Comment by medb** [comment]
No, this is oversight, we will fix it in next release. Thanks for reporting this issue!

**Comment by suztomo** [comment]
Thank you for confirming.
